### ISSUE TITLE
BFE protocols with EnTK -- Getting Started (1) 

### ISSUE THREAD

**Issue by shantenujha** [inspiremd/radical-inspire#2]
The following page should give you some information about Ensemble Toolkit, the workflow engine we spoke about in our past meeting. That is the system that requires RabbitMQ and that page should give you an idea of how it is used:

https://radicalentk.readthedocs.io/en/latest/entk.html

The following page gives you some more information about RADICAL-Pilot, the pilot-based runtime system used by EnTK to actually execute the tasks of the workflow on HPC machines. That page should give you an idea about what a pilot system is, why it is useful and why we need a MongoDB server:

https://radicalpilot.readthedocs.io/en/devel/overview.html

Further, these are commands that Matteo shared with Agastya and Mat on February 03.
---

Please export the following variables into your shell environment before using RCT. They should be picked up when you will run the examples shipped with EnTK:

export RADICAL_PILOT_DBURL= (removed for security)
export RMQ_HOSTNAME=(removed for security)
export RMQ_PORT=(removed for security)
Also, to facilitate debugging in case of issues, please export also the following:

export RADICAL_VERBOSE="DEBUG"
export RADICAL_LOG_LVL="DEBUG"
export RADICAL_LOG_TGT="radical.log"
export RADICAL_PROFILE="TRUE"

**Comment by bieniekmateusz** [comment]
Hi @shantenujha and @mturilli, thanks for creating this issue. Mat

**Comment by bieniekmateusz** [comment]
Thanks again for setting up everything and for your patience. 

I've created a virtual env and installed the radical.entk, and then sourced the variables you shared with me (mongodb, rabbitmq, etc). 

Then I downloaded the pipeline of ensembles examples from here https://radicalentk.readthedocs.io/en/latest/examples.html

The session was created: 
EnTK session: re.session.archy.dresio....
Creating AppManagerSetting up RabbitMQ system                                 ok
                                                                              ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                   n/a
new session: [re.session.archy.dresio....                             \
database   : [...@url:port/inspire]err
All components terminated

The first Exception is pymongo.errors.OperationFailure: Authentication failed in: 
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)

This error occured when handling the first: RuntimeError: session create failed [mongodb:...@url:port/inspire] in
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/pilot/session.py", line 186, in _initialize_primary
    raise RuntimeError ('session create failed [%s]' % dburl)

I do not have any ssh keys set up for this project. During each try a directory was created. 

The same error happens when the other EnTK example is tried. 


Do you know what I can do to get authenticated with your mongodb? 

Thank you,  Mat

**Comment by bieniekmateusz** [comment]
Hi there, 

I've just tried again and there is no change. 

We might consider setting up a server on my computer as well. Let's discuss this later during the voip!

**Comment by mturilli** [comment]
@bieniekmateusz , please substitute `one.radical-project.org` with `two.radical-project.org` in your `RADICAL_PILOT_DBURL` variable. Does this take your execution further?

**Comment by bieniekmateusz** [comment]
Hi @mturilli,

Thanks for getting back to me. 

I updated RADICAL_PILOT_DBURL as requested. I am afraid it ends with the same error. 

Best, Mat

**Comment by bieniekmateusz** [comment]
A quick update - I just run it again here with Shantenu, and it worked. There is a different error now. I have to do something and then look at it in a few hours:
```
EnTK session: re.session.archy.dresio.018317.0004
Creating AppManagerSetting up RabbitMQ system                                 ok
                                                                              ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                   n/a
new session: [re.session.archy.dresio.018317.0004]                             \
database   : [...]ok
create pilot manager                                                          ok
submit 1 pilot(s)
        All components terminated
Traceback (most recent call last):
  File "poe.py", line 117, in <module>
    appman.run()
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/entk/appman/appmanager.py", line 414, in run
    self._rmgr._submit_resource_request()
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/entk/execman/rp/resource_manager.py", line 171, in _submit_resource_request
    self._pilot = self._pmgr.submit_pilots(pdesc)
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/pilot/pilot_manager.py", line 551, in submit_pilots
    pilot = ComputePilot(pmgr=self, descr=pd)
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/pilot/compute_pilot.py", line 100, in __init__
    self._resource_sandbox = self._session._get_resource_sandbox(pilot)
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/pilot/session.py", line 772, in _get_resource_sandbox
    shell = self.get_js_shell(resource, schema)
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/pilot/session.py", line 818, in get_js_shell
    shell = rsup.PTYShell(js_url, self)
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/saga/utils/pty_shell.py", line 246, in __init__
    self.pty_shell  = self.factory.run_shell  (self.pty_info)
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/saga/utils/pty_shell_factory.py", line 465, in run_shell
    self._initialize_pty (sh_slave, info)
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/saga/utils/pty_shell_factory.py", line 428, in _initialize_pty
    raise ptye.translate_exception (e)
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/saga/utils/pty_shell_factory.py", line 301, in _initialize_pty
    raise rse.NoSuccess("Could not detect shell prompt (timeout)")
radical.saga.exceptions.NoSuccess: Could not detect shell prompt (timeout) (/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/saga/utils/pty_shell_factory.py +301 (_initialize_pty)  :  raise rse.NoSuccess("Could not detect shell prompt (timeout)"))
(radical)
```

I did not have a look at the code, but I wonder if it is related to me using zsh instead of bash etc. 

Thanks

**Comment by mturilli** [comment]
Thanks @bieniekmateusz. The new error tells us that SAGA is not able to detect a prompt on the machine on which you are trying to execute your application:
```
raise rse.NoSuccess("Could not detect shell prompt (timeout)")
```
What is this machine and from what machine are you executing your application? Can I have a link to the code of the application you are trying to execute?

**Comment by bieniekmateusz** [comment]
I am using the examples from https://radicalentk.readthedocs.io/en/latest/examples.html

This makes sense. Thanks, at the end - I submit the job to my own computer. 

So the next step is to change my resources to use Summit. 

I've updated therefore the resources keyword:
`'resource': 'summit.olcf.ornl.gov'`

This complains:

```
submit 1 pilot(s)
        All components terminated
Traceback (most recent call last):
  File "poe.py", line 117, in <module>
    appman.run()
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/entk/appman/appmanager.py", line 414, in run
    self._rmgr._submit_resource_request()
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/entk/execman/rp/resource_manager.py", line 171, in _submit_resource_request
    self._pilot = self._pmgr.submit_pilots(pdesc)
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/pilot/pilot_manager.py", line 551, in submit_pilots
    pilot = ComputePilot(pmgr=self, descr=pd)
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/pilot/compute_pilot.py", line 99, in __init__
    = self._session._get_jsurl           (pilot)
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/pilot/session.py", line 927, in _get_jsurl
    rcfg    = self.get_resource_config(resrc, schema)
  File "/home/dresio/software/virtualenvs/radical/lib/python3.8/site-packages/radical/pilot/session.py", line 648, in get_resource_config
    raise RuntimeError("Resource domain '%s' is unknown." % domain)
```


Thanks

**Comment by bieniekmateusz** [comment]
@apbhati this issue is used to track the progress with radical tools

**Comment by mturilli** [comment]
@bieniekmateusz, did you configure your account on local machine (it has to be a Linux-based OS) to ssh into localhost without a password? You may have noticed this is one of the requirements of EnTK and its runtime system RADICAL-Pilot (RP), see https://radicalpilot.readthedocs.io/en/stable/machconf.html#configuring-ssh-access and https://radicalentk.readthedocs.io/en/latest/install.html#preparing-the-environment. 

Let me give some rapid pointers on how I would proceed. Apologies in advance if all the following is already well-established.

I think using your linux local machine is a good starting point to get accustomed to RCT and to writing an application with them. I would suggest to:
- Configure your RCT stack locally as you are doing already
- Successfully execute an example of an EnTK application on your local machine. Are you following our EnTK user guide? If not, I would advice to do so. Consistently, I would suggest to run this example https://github.com/radical-cybertools/radical.entk/blob/devel/examples/user_guide/get_started.py, by following this documentation page: https://radicalentk.readthedocs.io/en/latest/user_guide/get_started.html.
- After that, try running the same example on Summit.

Please note:
- In order to execute your application on Summit you **cannot** use your local machine. You need first to ssh into one of Summit login nodes via your passowrd+token and then, from there, execute your application written with EnTK. 
- RCT and therefore EnTK are Python modules. You import those modules to write your own application, using their classes and methods. Once you wrote your application, you execute it as a normal python script. All the 'magic' happens within RCT: acquiring resources and scheduling the tasks of your application on those resources for execution.

Let me know how if this is clear. If it is not, I will be glad to enter in further details. If you get stuck, we can have a 1to1 support session for an hour and see whether that helps.

**Comment by mturilli** [comment]
Just checking whether everything is progressing well with this?

**Comment by apbhati1** [comment]
Hi all,

As Matteo suggested, I tried to install EnTK on Summit using conda following the steps mentioned in section 3.1.2 of the documentation. However, I encounter an error where the package is not found.

`conda install -c conda-forge radical.entk` gives the following error message:
```Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - radical.entk

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-ppc64le
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/omnia/linux-ppc64le
  - https://conda.anaconda.org/omnia/noarch
  - https://repo.anaconda.com/pkgs/main/linux-ppc64le
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-ppc64le
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Am I missing something here?

Thanks,
Agastya

**Comment by mturilli** [comment]
Hi @apbhati1, I do not use conda myself. Let me ping our conda maintainer and I will get right back to you.

**Comment by mturilli** [comment]
An update: we did not publish our stack for linux_ppc64 on conda-forge. We are now in the process of building out stack to publish it for that architecture. If you are in a hurry, you can just use `virtualenv` and skip conda altogether.

**Comment by mturilli** [comment]
We have requested for some of the dependencies of our stack to be built for powerpc (https://github.com/conda-forge/pymongo-feedstock/pulls). Until these dependencies are not available, we cannot publish our stack. I will update this ticket once the stack is available but we can not control how long it will take.
